<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Authors>meshmakers GmbH and Contributors</Authors>
        <Company>meshmakers GmbH</Company>
        <Configurations>Debug;Release;DebugL</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Meshmakers.Octo.Runtime.Contracts" Version="999.0.0.0"/>
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.SourceGeneration" OutputItemType="Analyzer" ReferenceOutputAssembly="false" Version="999.0.0.0"/>
        <PackageReference Include="Meshmakers.Octo.ConstructionKit.MsBuildTasks" Version="999.0.0.0" PrivateAssets="all"/>
        <PackageReference Include="Meshmakers.Octo.Sdk.Packages.Basic" Version="999.0.0"/>
    </ItemGroup>
    <ItemGroup>
        <ConstructionKitFolder Visible="false" Include="$(MSBuildProjectDirectory)\ConstructionKit"/>
    </ItemGroup>
</Project>